version: '3'

services:
  prometheus:
      container_name: prometheus
      image: prom/prometheus:latest
      restart: always
      ports:
      - 9090:9090
      volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/pure.rules:/etc/prometheus/pure.rules
      - prometheus_data:/prometheus
      command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=5d

  prometheus-alertmanager:
    container_name: prometheus-alertmanager
    image: prom/alertmanager:latest
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

  pure-exporter:
      container_name: pure-exporter
      image: genegatpure/pure-exporter
      restart: always
      ports:
      - 9491:9491

  pure-helper:
      container_name: pure-helper
      image: purestorage/pure-helper
      restart: always
      ports:
      - 9000:9000

  grafana:
      container_name: grafana
      image: grafana/grafana:latest
      restart: always
      depends_on:
      - prometheus
      ports:
      - 3000:3000
      volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana

volumes:
    grafana_data:
    prometheus_data:
    alertmanager_data:
